import { MigrationInterface, QueryRunner } from "typeorm";

export class FixJoinTableColumns1775682145076 implements MigrationInterface {
    name = 'FixJoinTableColumns1775682145076'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP CONSTRAINT "FK_f61e936ce48d1991852bb5c5fb6"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP CONSTRAINT "FK_e2871299792b20061c1e97b7fc0"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_3837ba993bd12d7398efc34cd95"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_aadc32f5893f6091d554e777ebc"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "FK_2b9db485ce959551f86a455481c"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "FK_81b3091098137d1f451377823f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b9db485ce959551f86a455481"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81b3091098137d1f451377823f"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP CONSTRAINT "UQ_aeca225c8cadd71c690c6b8c151"`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "description" character varying(160), "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "indications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d0dac99764b80fba94d3831dc2f" UNIQUE ("slug"), CONSTRAINT "PK_733e768d3d560472919502a0d66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."protocols_status_enum" AS ENUM('ORIGINAL', 'COMPLETED', 'CANCELLED', 'REMOVED')`);
        await queryRunner.query(`CREATE TABLE "protocols" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "document" character varying, "protocolNumber" character varying NOT NULL, "status" "public"."protocols_status_enum" NOT NULL DEFAULT 'ORIGINAL', "indicationId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_753d80f61205ed2b9c2277e01eb" UNIQUE ("protocolNumber"), CONSTRAINT "PK_69900eec42c88582ac8affff3e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "prefix" character varying NOT NULL, "slug" character varying NOT NULL, "name" character varying NOT NULL, "siteNumber" character varying, "patientCount" integer NOT NULL DEFAULT '0', "phoneNumber" character varying, "streetAddress" character varying, "city" character varying, "state" character varying, "zipCode" character varying, "link" character varying, "image" character varying, "indicationId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_26503a75e987672fb5af9258cc2" UNIQUE ("slug"), CONSTRAINT "PK_4f5eccb1dfde10c9170502595a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_usertype_enum" AS ENUM('TENANT_ADMIN', 'TENANT_STAFF', 'PATIENT', 'PRINCIPLE_INVESTIGATOR')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying(75) NOT NULL, "middleName" character varying(75), "lastName" character varying(75) NOT NULL, "email" character varying(191) NOT NULL, "password" character varying(191) NOT NULL, "phoneNumber" character varying(20), "isActive" boolean NOT NULL DEFAULT true, "emailVerifiedAt" TIMESTAMP, "lastLoginAt" TIMESTAMP, "userType" "public"."users_usertype_enum" NOT NULL DEFAULT 'TENANT_ADMIN', "roleId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."otps_purpose_enum" AS ENUM('general', 'verification', 'reset_password')`);
        await queryRunner.query(`CREATE TABLE "otps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(191) NOT NULL, "code" character varying(255) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "verified" boolean NOT NULL DEFAULT false, "purpose" "public"."otps_purpose_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_91fef5ed60605b854a2115d2410" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9bd09e59708ea02bb49081961c" ON "otps" ("email") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "site_protocols" ("protocol_id" uuid NOT NULL, "site_id" uuid NOT NULL, CONSTRAINT "PK_105c9899397748cb422e565d8fe" PRIMARY KEY ("protocol_id", "site_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_26112d59aea447e78647adc20b" ON "site_protocols" ("protocol_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7184a63c1aea2ff1cebf37c79" ON "site_protocols" ("site_id") `);
        await queryRunner.query(`CREATE TABLE "user_direct_permissions" ("user_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_0b531c0216e07393be09c0534fa" PRIMARY KEY ("user_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_47b237f7125b86dcac8ebb1065" ON "user_direct_permissions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_deb6ca01c22e7d8854b58a9c96" ON "user_direct_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_sites" ("user_id" uuid NOT NULL, "site_id" uuid NOT NULL, CONSTRAINT "PK_fb40cfe04628e6adefbe90c1eb4" PRIMARY KEY ("user_id", "site_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_876af02663eefdbbd607c73634" ON "user_sites" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_76a7e1a212a3784b96140b713b" ON "user_sites" ("site_id") `);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP COLUMN "admin_id"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP COLUMN "page_id"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "permission_groups" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "permission_groups" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "permission_groups" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "db_name"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "db_host"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "db_port"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "db_user"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "db_password"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "mongo_uri"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "permission_groups" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "PK_c65920faf34ab5601a43a9aefb3"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "PK_81b3091098137d1f451377823f6" PRIMARY KEY ("permissionGroupId")`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "PK_81b3091098137d1f451377823f6"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP COLUMN "permissionGroupId"`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD "adminId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD "pageId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "permission_groups" ADD "icon" character varying(60)`);
        await queryRunner.query(`ALTER TABLE "permission_groups" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permission_groups" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permission_groups" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "createdById" uuid`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "updatedById" uuid`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "dbName" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "dbHost" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "dbPort" integer NOT NULL DEFAULT '5432'`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "dbUser" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "dbPassword" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "mongoUri" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD "tenant_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "PK_e32843c6534f9029d4b7156b8d4" PRIMARY KEY ("tenant_id")`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD "permission_group_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "PK_e32843c6534f9029d4b7156b8d4"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "PK_cfba7adb874f2b6570ffff01521" PRIMARY KEY ("tenant_id", "permission_group_id")`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_0ce20ad956af3961df1ff12d0c5"`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "groupId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "groupId" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_e32843c6534f9029d4b7156b8d" ON "tenant_permission_groups" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf12c799d4f9053e7d5223fa25" ON "tenant_permission_groups" ("permission_group_id") `);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD CONSTRAINT "UQ_1616ca3fdccf296410efb9bc866" UNIQUE ("adminId", "pageId")`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD CONSTRAINT "FK_30b916ec242b9cd74b973ff184e" FOREIGN KEY ("adminId") REFERENCES "admins"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD CONSTRAINT "FK_f51a89b6fe7a429776a169c9c21" FOREIGN KEY ("pageId") REFERENCES "pages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_0ce20ad956af3961df1ff12d0c5" FOREIGN KEY ("groupId") REFERENCES "permission_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_c597309c51a8c262eb1892a96a4" FOREIGN KEY ("createdById") REFERENCES "admins"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_45fcc95155cf559f716cc3eaaf4" FOREIGN KEY ("updatedById") REFERENCES "admins"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "protocols" ADD CONSTRAINT "FK_d721341df568f28b79f8fefd43d" FOREIGN KEY ("indicationId") REFERENCES "indications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sites" ADD CONSTRAINT "FK_dbebf9dd6ece5b8577b8c11e7e4" FOREIGN KEY ("indicationId") REFERENCES "indications"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "FK_e32843c6534f9029d4b7156b8d4" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "FK_bf12c799d4f9053e7d5223fa25d" FOREIGN KEY ("permission_group_id") REFERENCES "permission_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site_protocols" ADD CONSTRAINT "FK_26112d59aea447e78647adc20bf" FOREIGN KEY ("protocol_id") REFERENCES "protocols"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "site_protocols" ADD CONSTRAINT "FK_b7184a63c1aea2ff1cebf37c793" FOREIGN KEY ("site_id") REFERENCES "sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_direct_permissions" ADD CONSTRAINT "FK_47b237f7125b86dcac8ebb10655" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_direct_permissions" ADD CONSTRAINT "FK_deb6ca01c22e7d8854b58a9c967" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_sites" ADD CONSTRAINT "FK_876af02663eefdbbd607c736346" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_sites" ADD CONSTRAINT "FK_76a7e1a212a3784b96140b713ba" FOREIGN KEY ("site_id") REFERENCES "sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_sites" DROP CONSTRAINT "FK_76a7e1a212a3784b96140b713ba"`);
        await queryRunner.query(`ALTER TABLE "user_sites" DROP CONSTRAINT "FK_876af02663eefdbbd607c736346"`);
        await queryRunner.query(`ALTER TABLE "user_direct_permissions" DROP CONSTRAINT "FK_deb6ca01c22e7d8854b58a9c967"`);
        await queryRunner.query(`ALTER TABLE "user_direct_permissions" DROP CONSTRAINT "FK_47b237f7125b86dcac8ebb10655"`);
        await queryRunner.query(`ALTER TABLE "site_protocols" DROP CONSTRAINT "FK_b7184a63c1aea2ff1cebf37c793"`);
        await queryRunner.query(`ALTER TABLE "site_protocols" DROP CONSTRAINT "FK_26112d59aea447e78647adc20bf"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "FK_bf12c799d4f9053e7d5223fa25d"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "FK_e32843c6534f9029d4b7156b8d4"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`ALTER TABLE "sites" DROP CONSTRAINT "FK_dbebf9dd6ece5b8577b8c11e7e4"`);
        await queryRunner.query(`ALTER TABLE "protocols" DROP CONSTRAINT "FK_d721341df568f28b79f8fefd43d"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_45fcc95155cf559f716cc3eaaf4"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_c597309c51a8c262eb1892a96a4"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_0ce20ad956af3961df1ff12d0c5"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP CONSTRAINT "FK_f51a89b6fe7a429776a169c9c21"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP CONSTRAINT "FK_30b916ec242b9cd74b973ff184e"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP CONSTRAINT "UQ_1616ca3fdccf296410efb9bc866"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf12c799d4f9053e7d5223fa25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e32843c6534f9029d4b7156b8d"`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "groupId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "groupId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_0ce20ad956af3961df1ff12d0c5" FOREIGN KEY ("groupId") REFERENCES "permission_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "PK_cfba7adb874f2b6570ffff01521"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "PK_e32843c6534f9029d4b7156b8d4" PRIMARY KEY ("tenant_id")`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP COLUMN "permission_group_id"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "PK_e32843c6534f9029d4b7156b8d4"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP COLUMN "tenant_id"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "mongoUri"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "dbPassword"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "dbUser"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "dbPort"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "dbHost"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "dbName"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "permission_groups" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "permission_groups" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "permission_groups" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "permission_groups" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP COLUMN "pageId"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" DROP COLUMN "adminId"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD "permissionGroupId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "PK_81b3091098137d1f451377823f6" PRIMARY KEY ("permissionGroupId")`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD "tenantId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" DROP CONSTRAINT "PK_81b3091098137d1f451377823f6"`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "PK_c65920faf34ab5601a43a9aefb3" PRIMARY KEY ("tenantId", "permissionGroupId")`);
        await queryRunner.query(`ALTER TABLE "permission_groups" ADD "icon" character varying(60)`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "mongo_uri" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "db_password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "db_user" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "db_port" integer NOT NULL DEFAULT '5432'`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "db_host" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "db_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "updated_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "permission_groups" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "permission_groups" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permission_groups" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "group_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD "page_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD "admin_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "updated_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "created_by_id" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76a7e1a212a3784b96140b713b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_876af02663eefdbbd607c73634"`);
        await queryRunner.query(`DROP TABLE "user_sites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deb6ca01c22e7d8854b58a9c96"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47b237f7125b86dcac8ebb1065"`);
        await queryRunner.query(`DROP TABLE "user_direct_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7184a63c1aea2ff1cebf37c79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26112d59aea447e78647adc20b"`);
        await queryRunner.query(`DROP TABLE "site_protocols"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bd09e59708ea02bb49081961c"`);
        await queryRunner.query(`DROP TABLE "otps"`);
        await queryRunner.query(`DROP TYPE "public"."otps_purpose_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_usertype_enum"`);
        await queryRunner.query(`DROP TABLE "sites"`);
        await queryRunner.query(`DROP TABLE "protocols"`);
        await queryRunner.query(`DROP TYPE "public"."protocols_status_enum"`);
        await queryRunner.query(`DROP TABLE "indications"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD CONSTRAINT "UQ_aeca225c8cadd71c690c6b8c151" UNIQUE ("admin_id", "page_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_81b3091098137d1f451377823f" ON "tenant_permission_groups" ("permissionGroupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b9db485ce959551f86a455481" ON "tenant_permission_groups" ("tenantId") `);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "FK_81b3091098137d1f451377823f6" FOREIGN KEY ("permissionGroupId") REFERENCES "permission_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tenant_permission_groups" ADD CONSTRAINT "FK_2b9db485ce959551f86a455481c" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_aadc32f5893f6091d554e777ebc" FOREIGN KEY ("updated_by_id") REFERENCES "admins"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_3837ba993bd12d7398efc34cd95" FOREIGN KEY ("created_by_id") REFERENCES "admins"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD CONSTRAINT "FK_e2871299792b20061c1e97b7fc0" FOREIGN KEY ("page_id") REFERENCES "pages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_permissions" ADD CONSTRAINT "FK_f61e936ce48d1991852bb5c5fb6" FOREIGN KEY ("admin_id") REFERENCES "admins"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
